#!/usr/bin/env bash

which -s rvm
if [[ $? != 0 ]] ; then
  ./ensure-gpg
  command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
  command curl -sSL https://get.rvm.io | bash -s stable --ruby
  source $HOME/.rvm/scripts/rvm
fi
